"""Generate webapp/data.js from the shared lexicon and the sample requirement set.

Keeping one lexicon file guarantees the Python classifier and the web app agree.
Usage: python tools/build_web_data.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
lexicon = json.loads((ROOT / "ram" / "lexicon.json").read_text(encoding="utf-8"))
sample = json.loads((ROOT / "examples" / "campusconnect.json").read_text(encoding="utf-8"))
out = "// Generated by tools/build_web_data.py - do not edit by hand.\nwindow.RAM_DATA = " + \
      json.dumps({"lexicon": lexicon, "sample": sample}, indent=1) + ";\n"
(ROOT / "webapp" / "data.js").write_text(out, encoding="utf-8")
print("wrote webapp/data.js", len(out), "bytes")
