// Generated by tools/build_web_data.py - do not edit by hand.
window.RAM_DATA = {
 "lexicon": {
  "note": "Weighted cue lexicon shared by the Python classifier and the web app. Patterns are regular expressions matched case-insensitively against the requirement text.",
  "product": [
   [
    "\\b(goal|goals|vision|strategy|strategic|strategically)\\b",
    2.0
   ],
   [
    "\\b(business|market|competitive|compete|competitors?|brand|revenue)\\b",
    1.8
   ],
   [
    "\\b(organi[sz]ation|organi[sz]ational|institution|stakeholders?|management)\\b",
    1.5
   ],
   [
    "\\b(retention|adoption|satisfaction|trustworthy|reputation|long-term)\\b",
    1.6
   ],
   [
    "\\b(increase|improve|reduce|strengthen|become|establish|ensure)\\b",
    0.9
   ],
   [
    "\\bcompl(y|ies|iance)\\b",
    0.8
   ],
   [
    "\\b(platform|overall|preferred|channel)\\b",
    0.6
   ]
  ],
  "feature": [
   [
    "\\b(feature|capability|capabilities|module|portal|service|workflow|dashboard)\\b",
    1.6
   ],
   [
    "\\b(support|supports|provide|provides|offers?|includes?)\\b",
    1.1
   ],
   [
    "\\b(enable|enables|allow|allows)\\b",
    1.0
   ],
   [
    "\\b(integrat\\w+|personali[sz]ed|multi-language|accessibility|notification centre)\\b",
    1.3
   ],
   [
    "\\b(manage|management|matching|planning)\\b",
    0.7
   ]
  ],
  "function": [
   [
    "\\b(shall|must)\\b",
    0.8
   ],
   [
    "\\b(user|student|users|students) (can|shall|is able|should be able)\\b",
    1.8
   ],
   [
    "\\b(the system|system) shall\\b",
    1.2
   ],
   [
    "\\b(display|displays|show|shows|send|sends|validate|calculate|submit|select|click|tap|taps|swip\\w+|upload|download|search|sort|filter|log in|log out|reset|confirm|mark)\\b",
    1.3
   ],
   [
    "\\b(button|field|fields|form|screen|page|message|drop-down|link|list|banner)\\b",
    1.3
   ],
   [
    "\\b(when|if|after|before|while)\\b",
    0.5
   ]
  ],
  "component": [
   [
    "\\b\\d+(\\.\\d+)?\\s?(ms|s|sec|seconds|minutes|mb|gb|kb|%|replicas|messages|records|attempts|times)\\b",
    2.6
   ],
   [
    "\\b(http|https|rest|json|sql|sqlite|redis|api|tls|ssl|aes|jwt|oauth|pkce|smtp|ttl|lru|cpu|bcrypt|hash(es)?)\\b",
    1.9
   ],
   [
    "\\b(database|table|schema|index|indexed|cache|queue|thread|endpoint|protocol|algorithm|object storage|gateway|adapter|replica|constraint|foreign key)\\b",
    1.4
   ],
   [
    "\\b(latency|throughput|encrypt\\w*|retry|p95|percentile|utili[sz]ation)\\b",
    1.6
   ],
   [
    "\\b(class|component|client|layer|returns?)\\b",
    0.5
   ]
  ]
 },
 "sample": {
  "name": "CampusConnect",
  "requirements": [
   {
    "id": "P1",
    "title": "Improve student engagement with campus services",
    "description": "Increase the share of students who use campus services digitally, supporting the university strategy of a student-centred digital campus.",
    "level": 1,
    "parent": null,
    "status": "accepted",
    "value": 9,
    "cost": 8,
    "risk": 4,
    "source": "Strategy board",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "P2",
    "title": "Reduce administrative cost of student support",
    "description": "Reduce the operational cost to the organization of handling routine enquiries and bookings through self-service.",
    "level": 1,
    "parent": null,
    "status": "accepted",
    "value": 8,
    "cost": 8,
    "risk": 4,
    "source": "Operations",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "P3",
    "title": "Ensure trusted handling of student data",
    "description": "Maintain stakeholder trust and regulatory compliance in how student information is collected and protected.",
    "level": 1,
    "parent": null,
    "status": "accepted",
    "value": 9,
    "cost": 7,
    "risk": 6,
    "source": "Legal",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "P4",
    "title": "Establish a competitive mobile-first campus platform",
    "description": "Position the university against competing institutions as a leader in mobile-first services to support recruitment and retention.",
    "level": 1,
    "parent": null,
    "status": "accepted",
    "value": 7,
    "cost": 8,
    "risk": 5,
    "source": "Marketing",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "F1",
    "title": "Timetable and event management",
    "description": "The app supports personal timetable management and the discovery of campus events.",
    "level": 2,
    "parent": "P1",
    "status": "accepted",
    "value": 8,
    "cost": 6,
    "risk": 3,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "F2",
    "title": "Push notification service",
    "description": "Enable personalised notifications about deadlines, cancellations and events.",
    "level": 2,
    "parent": "P1",
    "status": "accepted",
    "value": 7,
    "cost": 5,
    "risk": 3,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "F3",
    "title": "Room and resource booking",
    "description": "Allow students to book study rooms and equipment without staff intervention.",
    "level": 2,
    "parent": "P2",
    "status": "accepted",
    "value": 8,
    "cost": 6,
    "risk": 4,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "F4",
    "title": "Helpdesk self-service portal",
    "description": "Provide a support capability that answers common questions and routes tickets to staff.",
    "level": 2,
    "parent": "P2",
    "status": "accepted",
    "value": 7,
    "cost": 6,
    "risk": 4,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "F5",
    "title": "Single sign-on and identity management",
    "description": "Support university single sign-on so that one identity provides access to every service.",
    "level": 2,
    "parent": "P3",
    "status": "accepted",
    "value": 9,
    "cost": 5,
    "risk": 5,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "F6",
    "title": "Privacy and consent management",
    "description": "Enable students to review and control the personal data the platform collects.",
    "level": 2,
    "parent": "P3",
    "status": "accepted",
    "value": 8,
    "cost": 5,
    "risk": 5,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "F7",
    "title": "Offline-first mobile experience",
    "description": "Support the core features when network connectivity is limited.",
    "level": 2,
    "parent": "P4",
    "status": "accepted",
    "value": 6,
    "cost": 6,
    "risk": 6,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "F8",
    "title": "Campus map and navigation",
    "description": "Provide indoor and outdoor navigation between campus locations.",
    "level": 2,
    "parent": "P4",
    "status": "accepted",
    "value": 6,
    "cost": 6,
    "risk": 4,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "FN1",
    "title": "Display weekly timetable",
    "description": "The system shall display the student's weekly timetable grouped by day.",
    "level": 3,
    "parent": "F1",
    "status": "accepted",
    "value": 9,
    "cost": 3,
    "risk": 1,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Entries are grouped Monday to Sunday",
     "Empty days show a placeholder"
    ]
   },
   {
    "id": "FN2",
    "title": "Add event to timetable",
    "description": "The user can add a campus event to their timetable by selecting the Add button on the event page.",
    "level": 3,
    "parent": "F1",
    "status": "accepted",
    "value": 6,
    "cost": 2,
    "risk": 1,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Added event appears in the weekly view"
    ]
   },
   {
    "id": "FN3",
    "title": "Highlight timetable clashes",
    "description": "The system shall highlight clashes and display a warning message when two entries overlap.",
    "level": 3,
    "parent": "F1",
    "status": "accepted",
    "value": 7,
    "cost": 3,
    "risk": 2,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Overlapping entries are marked in red",
     "Warning lists both entries"
    ]
   },
   {
    "id": "FN4",
    "title": "Notify lecture cancellations",
    "description": "The system shall send a push notification to affected students when a lecturer cancels a lecture.",
    "level": 3,
    "parent": "F2",
    "status": "accepted",
    "value": 9,
    "cost": 5,
    "risk": 4,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Only enrolled students are notified"
    ]
   },
   {
    "id": "FN5",
    "title": "Choose notification categories",
    "description": "The user can select which notification categories to receive on the settings screen.",
    "level": 3,
    "parent": "F2",
    "status": "accepted",
    "value": 5,
    "cost": 2,
    "risk": 1,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Preferences persist across sessions"
    ]
   },
   {
    "id": "FN6",
    "title": "Search available rooms",
    "description": "The user shall be able to search available rooms by date, time and capacity.",
    "level": 3,
    "parent": "F3",
    "status": "accepted",
    "value": 8,
    "cost": 3,
    "risk": 2,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Results respect all three filters"
    ]
   },
   {
    "id": "FN7",
    "title": "Confirm booking",
    "description": "The system shall confirm a booking and send an email receipt when the user submits a valid request.",
    "level": 3,
    "parent": "F3",
    "status": "accepted",
    "value": 8,
    "cost": 3,
    "risk": 2,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Receipt contains room, date and time"
    ]
   },
   {
    "id": "FN8",
    "title": "Prevent double booking",
    "description": "The system shall validate that a room is not double-booked before accepting a reservation.",
    "level": 3,
    "parent": "F3",
    "status": "accepted",
    "value": 9,
    "cost": 3,
    "risk": 3,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Conflicting request is rejected with an explanatory message"
    ]
   },
   {
    "id": "FN9",
    "title": "Submit support ticket",
    "description": "The user can submit a support ticket by completing the category and description fields.",
    "level": 3,
    "parent": "F4",
    "status": "accepted",
    "value": 7,
    "cost": 3,
    "risk": 1,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Ticket number is shown on submission"
    ]
   },
   {
    "id": "FN10",
    "title": "Suggest help articles",
    "description": "The system shall display suggested help articles while the user types a ticket description.",
    "level": 3,
    "parent": "F4",
    "status": "accepted",
    "value": 6,
    "cost": 5,
    "risk": 4,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "FN11",
    "title": "Log in with university credentials",
    "description": "The user shall log in by entering university credentials on the sign-in screen.",
    "level": 3,
    "parent": "F5",
    "status": "accepted",
    "value": 10,
    "cost": 3,
    "risk": 3,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Invalid credentials show an error message"
    ]
   },
   {
    "id": "FN12",
    "title": "Auto log-out after inactivity",
    "description": "The system shall log the user out after a period of inactivity and display a confirmation message.",
    "level": 3,
    "parent": "F5",
    "status": "accepted",
    "value": 6,
    "cost": 2,
    "risk": 2,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Message shown on next launch"
    ]
   },
   {
    "id": "FN13",
    "title": "Download personal data",
    "description": "The user can download a copy of their personal data from the privacy screen.",
    "level": 3,
    "parent": "F6",
    "status": "accepted",
    "value": 7,
    "cost": 4,
    "risk": 4,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Archive contains all stored personal data"
    ]
   },
   {
    "id": "FN14",
    "title": "Offline timetable",
    "description": "The system shall display cached timetable data and show an offline banner when no connection is available.",
    "level": 3,
    "parent": "F7",
    "status": "accepted",
    "value": 6,
    "cost": 4,
    "risk": 3,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Banner disappears on reconnect"
    ]
   },
   {
    "id": "FN15",
    "title": "Find building",
    "description": "The user can search for a building by name and select it to view directions.",
    "level": 3,
    "parent": "F8",
    "status": "accepted",
    "value": 5,
    "cost": 4,
    "risk": 3,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "C1",
    "title": "Timetable API latency",
    "description": "The timetable service shall respond to GET /timetable requests in under 300 ms for 95% of calls with a JSON payload.",
    "level": 4,
    "parent": "FN1",
    "status": "accepted",
    "value": 6,
    "cost": 2,
    "risk": 2,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "p95 latency below 300 ms in load test"
    ]
   },
   {
    "id": "C2",
    "title": "Clash detection query",
    "description": "Clash detection shall run an interval-overlap check over the entries table using an indexed start_time column.",
    "level": 4,
    "parent": "FN3",
    "status": "accepted",
    "value": 5,
    "cost": 2,
    "risk": 2,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Query plan uses the index"
    ]
   },
   {
    "id": "C3",
    "title": "Push delivery pipeline",
    "description": "Notifications shall be delivered through Firebase Cloud Messaging using a message queue with up to 3 retry attempts.",
    "level": 4,
    "parent": "FN4",
    "status": "accepted",
    "value": 6,
    "cost": 3,
    "risk": 4,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Failed pushes are retried 3 times"
    ]
   },
   {
    "id": "C4",
    "title": "Email receipt transport",
    "description": "Receipts shall be sent via SMTP over TLS by a background worker thread.",
    "level": 4,
    "parent": "FN7",
    "status": "accepted",
    "value": 4,
    "cost": 2,
    "risk": 2,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Receipt sent within 60 seconds"
    ]
   },
   {
    "id": "C5",
    "title": "Booking uniqueness constraint",
    "description": "The bookings table shall enforce a unique constraint on room_id and time_slot to prevent double-booking at the database level.",
    "level": 4,
    "parent": "FN8",
    "status": "accepted",
    "value": 7,
    "cost": 1,
    "risk": 1,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Duplicate insert raises constraint error"
    ]
   },
   {
    "id": "C6",
    "title": "OAuth 2.0 with PKCE",
    "description": "Authentication shall use the OAuth authorization code flow with PKCE and issue JWT access tokens valid for 15 minutes.",
    "level": 4,
    "parent": "FN11",
    "status": "accepted",
    "value": 8,
    "cost": 4,
    "risk": 4,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Tokens expire after 15 minutes"
    ]
   },
   {
    "id": "C7",
    "title": "Session expiry",
    "description": "Session tokens shall expire after 20 minutes of inactivity and be invalidated on the server.",
    "level": 4,
    "parent": "FN12",
    "status": "accepted",
    "value": 5,
    "cost": 1,
    "risk": 1,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Expired token returns 401"
    ]
   },
   {
    "id": "C8",
    "title": "Encrypted data export",
    "description": "Personal data export shall be generated as a JSON archive encrypted with AES-256 and deleted after 24 hours.",
    "level": 4,
    "parent": "FN13",
    "status": "accepted",
    "value": 6,
    "cost": 3,
    "risk": 4,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Archive unreadable without key"
    ]
   },
   {
    "id": "C9",
    "title": "Local cache store",
    "description": "The client shall cache timetable data in an SQLite database with a maximum size of 50 MB.",
    "level": 4,
    "parent": "FN14",
    "status": "accepted",
    "value": 5,
    "cost": 2,
    "risk": 2,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Cache never exceeds 50 MB"
    ]
   },
   {
    "id": "C10",
    "title": "Shortest-path routing",
    "description": "The routing component shall compute shortest paths on the campus graph using Dijkstra's algorithm and return results within 500 ms.",
    "level": 4,
    "parent": "FN15",
    "status": "accepted",
    "value": 4,
    "cost": 3,
    "risk": 3,
    "source": "Workshop",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "N1",
    "title": "Students want the app to be fast",
    "description": "Students say the app should feel fast and responsive.",
    "level": 3,
    "parent": null,
    "status": "new",
    "value": 5,
    "cost": 3,
    "risk": 3,
    "source": "Survey",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "N2",
    "title": "Integrate with the Moodle LMS",
    "description": "Allow course deadlines from the learning management system to appear in the timetable.",
    "level": 3,
    "parent": null,
    "status": "new",
    "value": 7,
    "cost": 5,
    "risk": 4,
    "source": "Lecturers",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "N3",
    "title": "Use Redis for caching timetable queries",
    "description": "The timetable service shall cache query results in Redis with a TTL of 10 minutes.",
    "level": 3,
    "parent": null,
    "status": "new",
    "value": 4,
    "cost": 2,
    "risk": 2,
    "source": "Developers",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "N4",
    "title": "User selects notification categories",
    "description": "The user can select which notification categories to receive on the settings screen.",
    "level": 3,
    "parent": null,
    "status": "new",
    "value": 5,
    "cost": 2,
    "risk": 1,
    "source": "Support",
    "rationale": "",
    "acceptance": []
   },
   {
    "id": "FN16",
    "title": "Export timetable to calendar",
    "description": "The user can export the weekly timetable to an iCalendar file from the timetable screen.",
    "level": 3,
    "parent": null,
    "status": "accepted",
    "value": 5,
    "cost": 3,
    "risk": 2,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "File opens in common calendar apps"
    ]
   },
   {
    "id": "C11",
    "title": "Rate limiting",
    "description": "The API gateway shall reject more than 100 requests per minute per client with HTTP 429.",
    "level": 4,
    "parent": "F3",
    "status": "accepted",
    "value": 5,
    "cost": 2,
    "risk": 3,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Client receives 429 above the limit"
    ]
   },
   {
    "id": "FN17",
    "title": "Notification preferences",
    "description": "The user can select which notification categories to receive on the settings screen.",
    "level": 3,
    "parent": "F2",
    "status": "accepted",
    "value": 5,
    "cost": 2,
    "risk": 1,
    "source": "Workshop",
    "rationale": "",
    "acceptance": [
     "Preferences persist"
    ]
   }
  ]
 }
};
